version: '0.1.{build}'
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  verbosity: minimal

# scripts to run before build
before_build:
  - cmd: dotnet --version
  - cmd: cd ./TodoApp
  - cmd: nuget restore
  
test:
  # only assemblies to test
  assemblies:
    - '**\*.Tests.dll'

deploy: off